# Site settings
title: angrypark's blog
SEOTitle: angrypark's blog
header-img: img/home-bg.jpg
email: sungnam1108@gmail.com
description: "머신러닝(추천시스템, 자연어처리) 논문 리뷰, 개발 관련 포스팅을 하고 있습니다."
keyword: "머신러닝, 추천시스템, 딥러닝, 자연어처리, ML"
url: "https://angrypark.github.io" # your host, for absolute URL
baseurl: "" # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
github_username: angrypark
facebook_username: sungnam1108
linkedin_username: angrypark

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  [
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "README.md",
  ]
anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Disqus settings
disqus_username: angrypark

# Netease settings
netease_comment: false

# Analytics settings
# Baidu Analytics
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: "UA-238690149-1" # Format: UA-xxxxxx-xx
ga_domain: angrypark.github.io

# Sidebar settings
sidebar: true # whether or not using Sidebar.
sidebar-about-description: "Machine Learning Engineer @daangn"
sidebar-avatar: https://github.com/angrypark.png # use absolute URL, seeing it's used in both `/` and `/about/`

# Featured Tags
featured-tags: true # whether or not using Feature-Tags
featured-condition-size: 2 # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: true
mathjax: true

# Friends
friends:
  []
